### PR TITLE
MySQL optimizations, Automatic conversion to binary UUID storage, Colored wool drop multiplication

### PR DESCRIPTION
**Pull request by Justin42**
Hello!

This PR merges in a number of mySQL optimizations from Stealth2800. There are also a number of other changes including:
- Automatic conversion of current databases to binary UUID storage. 
- Fixes colored wool drops
- Replaces deprecated API calls for action bar messages
- Removes initialization for new random instances on every sheep shear

_Special testing needs to be done for the UUID conversion, and regression for issue #184 (this uses the Paper event to handle that issue)_

This is a rather large PR that needs some additional review, so I don't suggest pulling it just yet. Still, my testing has gone well. Please let me know if you have any issues. Overall I believe this will be a big improvement.

### CODE REVIEW

**Comment by Justin42** [comment]
Truncating the mySQL table doesn't seem to actually solve anything, since all the data is already loaded at start up. So any data that gets truncated will just be readded on save. I can't think of any good solution to that except better handling for entity removals. I will merge in your solution to #184 soon.

**Comment by Nathat23** [comment]
Is this ready to merge in yet or not?

**Comment by Justin42** [comment]
Current database conversion and entity removal still needs testing.

**Comment by Nathat23** [comment]
I have fixed the issues with converting the database, and have now merged this into the 3.4 branch, https://github.com/Nathat23/StackMob-3/commit/61184a4f00bd54e331d62622df6f90e17a2a5609

Thank you @Justin42 and @Stealth2800 for your very helpful contributions!

**Comment by Stealth2800** [comment]
@Justin42 Regarding https://github.com/Nathat23/StackMob-3/pull/213/commits/c5b0cbd48a47cc068f9cf806c9f8ffdfeecc1fbb - the try-with-resources block was very much intended in order to auto close the `PreparedStatement` (which you aren't even doing anymore). The PreparedStatements should be closed to avoid resource leaks, but there's a number of them that aren't being closed as of the latest version now.

**Comment by Nathat23** [comment]
> @Justin42 Regarding [c5b0cbd](https://github.com/Nathat23/StackMob-3/commit/c5b0cbd48a47cc068f9cf806c9f8ffdfeecc1fbb) - the try-with-resources block was very much intended in order to auto close the `PreparedStatement` (which you aren't even doing anymore). The PreparedStatements should be closed to avoid resource leaks, but there's a number of them that aren't being closed as of the latest version now.

I have fixed this in https://github.com/Nathat23/StackMob-3/commit/a88daa03f23e796a2bce15824544ca0983ff0a26

**Pull request closed without merging**
