### PR TITLE
Should fix issue #236

### PR DESCRIPTION
**Pull request by Aurelien30000**
Use the Bukkit Api to create the file instead of an InputStream. https://github.com/Nathat23/StackMob-3/issues/236

### CODE REVIEW

**Comment by Nathat23** [comment]
This won't work for the languages files though?

**Comment by Aurelien30000** [comment]
Yeah indeed, I'am finding something else

**Comment by Aurelien30000** [comment]
Done :)

**Comment by Nathat23** [comment]
Thanks.

**Pull request merged**
